name: Deploy Alvegest via SFTP

on:
  push:
    branches:
      - principale  # Uso 'principale' perchÃ© il tuo ramo su GitHub si chiama cosÃ¬

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Recupero codice
        uses: actions/checkout@v3

      - name: ðŸš€ Invio file al NAS via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_SERVER }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22
          local_path: './'
          remote_path: '/web/alvegest'
          sftp_args: '-o ConnectTimeout=5'
